--DROP TABLE [EA2A-GRUPO2].dbo.TM_PROYECTO;
CREATE TABLE [EA2A-GRUPO2].dbo.TM_PROYECTO (
	IDPROYECTO int IDENTITY(1,1) NOT NULL,
	TIPOPROYECTO varchar(100) NULL,
	IDEMPRESA int NULL,
	AREAEMPRESA varchar(100) NULL,
	JEFEPROYECTO VARCHAR(256) NULL,
	IDSERVICIO int NULL,
	FECHAINICIOPLAN varchar(20) NULL,
	FECHAINICIOREAL varchar(20) NULL,
	FECHAFINPLAN varchar(20) NULL,
	FECHAFINREAL varchar(20) NULL,
	ACTIVO bit NULL,
	USUARIOCREA int NULL,
	USUARIOMODIFICA int NULL,
	FECHACREA datetime NULL,
	FECHAMODIFICA datetime NULL,
	CONSTRAINT PK__TM_PROYE__0C889540EFD2AA62 PRIMARY KEY (IDPROYECTO)
);

--DROP TABLE [EA2A-GRUPO2].dbo.TM_DETALLE_PROYECTO;
CREATE TABLE [EA2A-GRUPO2].dbo.TM_DETALLE_PROYECTO (
	IDDETALLEPROYECTO int IDENTITY(1,1) NOT NULL,
	IDPROYECTO int  NOT NULL,
	FASEPROYECTO varchar(50) NULL,
	DESCRIPCIONHITO varchar(100) NULL,
	PROGRESO varchar(10) NULL,
	FECHAPLANHITO varchar(20) NULL,
	FECHAREALHITO varchar(20) NULL,
	ACTIVO bit NULL,
	USUARIOCREA int NULL,
	USUARIOMODIFICA int NULL,
	FECHACREA datetime NULL,
	FECHAMODIFICA datetime NULL,
	CONSTRAINT PK__TM_DET__0C889540EFD2AA62 PRIMARY KEY (IDDETALLEPROYECTO)
);


--DROP TABLE [EA2A-GRUPO2].dbo.TM_EMPRESA;
CREATE TABLE [EA2A-GRUPO2].dbo.TM_EMPRESA (
	IDEMPRESA int IDENTITY(1,1) NOT NULL,
	RUC varchar(20) NULL,
	RAZONSOCIAL varchar(250) NULL,
	RUTAIMAGEN varchar(250) NULL,
	EMAIL varchar(100) NULL,
	ACTIVO bit NULL,
	USUARIOCREA int NULL,
	USUARIOMODIFICA int NULL,
	FECHACREA datetime NULL,
	FECHAMODIFICA datetime NULL,
	CONSTRAINT PK__TM_EMPR__0C889540EFD2AA62 PRIMARY KEY (IDEMPRESA)
);

--DROP TABLE [EA2A-GRUPO2].dbo.TM_SERVICIO;
CREATE TABLE [EA2A-GRUPO2].dbo.TM_SERVICIO (
	IDSERVICIO int IDENTITY(1,1) NOT NULL,
	NOMBRE varchar(100) NULL,
	DESCRIPCION varchar(250) NULL,
	RUTAIMAGEN varchar(250) NULL,
	ACTIVO bit NULL,
	USUARIOCREA int NULL,
	USUARIOMODIFICA int NULL,
	FECHACREA datetime NULL,
	FECHAMODIFICA datetime NULL,
	CONSTRAINT PK__TM_SERV__0C889540EFD2AA62 PRIMARY KEY (IDSERVICIO)
);


CREATE TABLE [EA2A-GRUPO2].dbo.TM_USUARIO (
	IDUSUARIO int IDENTITY(1,1) NOT NULL,
	NOMBRES varchar(250) NULL,
	APELLIDOS varchar(250) NULL,
	EMAIL varchar(100) NULL,
	TELEFONO varchar(20) NULL,
	IDEMPRESA int NULL,
	ACTIVO bit NULL,
	USUARIOCREA int NULL,
	USUARIOMODIFICA int NULL,
	FECHACREA datetime NULL,
	FECHAMODIFICA datetime NULL,
	CONSTRAINT PK__TM_USUA__0C889540EFD2AA62 PRIMARY KEY (IDUSUARIO)
);
